import {
  analyzeSolanaTransactionFunction,
  solanaAccountHistoryFunction,
  solanaTxToMermaidFunction,
  solanaHistoryInsightsFunction,
  solanaTxClassifyExpertFunction,
  solanaTxExpertAnalyzeFunction,
  modelProviderSelectorFunction,
  solanaWalletConnectFunction,
  solanaSendTransactionFunction,
  gpt4oMiniFunction,
  gptO1MiniFunction,
  claude35SonnetFunction,
  claude37SonnetFunction,
  gemini20FlashFunction,
  gemini15ProFunction,
  mixtureMultiChainExpert1Function,
  mixtureMultiChainExpert1ProFunction,
} from "./solana-functions";

export const nodeFunctions = [
  analyzeSolanaTransactionFunction,
  solanaAccountHistoryFunction,
  solanaTxToMermaidFunction,
  solanaHistoryInsightsFunction,
  solanaTxClassifyExpertFunction,
  solanaTxExpertAnalyzeFunction,
  modelProviderSelectorFunction,
  solanaWalletConnectFunction,
  solanaSendTransactionFunction,
  gpt4oMiniFunction,
  gptO1MiniFunction,
  claude35SonnetFunction,
  claude37SonnetFunction,
  gemini20FlashFunction,
  gemini15ProFunction,
  mixtureMultiChainExpert1Function,
  mixtureMultiChainExpert1ProFunction,
];

export { solanaWalletConnectFunction, solanaSendTransactionFunction } from "./solana-functions";
